spelling=Kontrolkirina rastniv\u00EEs\u00EA
hlp_grammar=Z\u00EAdetir \u015Fa\u015F\u00EEy\u00EAn rastniv\u00EEs\u00EE kontrol bike
grammar=Possible mistakes
hlp_cap=Check missing capitalization of sentences.
cap=Bikaran\u00EEna herf\u00EAn mezin
hlp_dup=Peyv\u00EAn dubarekir\u00EE kontrol bike.
dup=Peyv\u00EAn dubarekir\u00EE
hlp_pair=Parantez \u00FB dunik\u00EAn k\u00EAm \u00FB y\u00EAn b\u00EEleseba kontrol bike.
pair=Parantezan
punctuation=Niqte\u015Fan\u00EE
hlp_spaces=Check single spaces between words.
spaces=Word spacing
hlp_mdash=Force unspaced em dash instead of spaced en dash.
mdash=Em dash
hlp_ndash=Force spaced en dash instead of unspaced em dash.
ndash=Bendik
hlp_quotation=Dunikan kontrol bikin: "x" \u2192 \u201Cx\u201D
quotation=Quotation marks
hlp_times=Check true multiplication sign: 5x5 \u2192 5\u00D75
times=Multiplication sign
hlp_spaces2=Check single spaces between sentences.
spaces2=Sentence spacing
hlp_spaces3=Check more than two extra space characters between words and sentences.
spaces3=More spaces
hlp_minus=Change hyphen characters to real minus signs.
minus=Minus sign
hlp_apostrophe=Change typewriter apostrophe, single quotation marks and correct double primes.
apostrophe=Apostrophe
hlp_ellipsis=Replace three dots with ellipsis.
ellipsis=S\u00EAxal
others=\u00CA din
hlp_metric=Measurement conversion from \u00B0F, mph, ft, in, lb, gal and miles.
metric=Convert to metric (\u00B0C, km/h, m, kg, l)
hlp_numsep=Gelemper\u00EE (1000000 \u2192 1,000,000) an j\u00EE ISO (1000000 \u2192 1 000 000).
numsep=Thousand separation of large numbers
hlp_nonmetric=Measurement conversion from \u00B0C; km/h; cm, m, km; kg; l.
nonmetric=Convert to non-metric (\u00B0F, mph, ft, lb, gal)
