directories:
  output: dist_electron
  buildResources: build
appId: com.converttool.app
productName: 文档转换器
extraResources:
  - from: resources/backend/dist
    to: backend/dist
  - from: 更新/更新/通用更新组件/updater.exe
    to: updater.exe
files:
  - filter:
      - package.json
      - electron/**/*
      - frontend/dist/**/*
compression: store
win:
  icon: frontend/public/app.ico
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  unicode: true
  createDesktopShortcut: always
  createStartMenuShortcut: true
  shortcutName: 文档转换器
  allowElevation: true
  runAfterFinish: false
  artifactName: ${productName}-Setup-${version}.${ext}
electronVersion: 28.3.3
